In [18]:
# Install gensim
%pip install gensim

# Import Word2Vec
from gensim.models import Word2Vec

print("Word2Vec imported successfully!")

Requirement already satisfied: gensim in c:\users\wenur\appdata\local\programs\python\python313\lib\site-packages (4.4.0)
Requirement already satisfied: numpy>=1.18.5 in c:\users\wenur\appdata\local\programs\python\python313\lib\site-packages (from gensim) (2.5.2)
Requirement already satisfied: scipy>=1.7.0 in c:\users\wenur\appdata\local\programs\python\python313\lib\site-packages (from gensim) (1.18.1)
Requirement already satisfied: smart_open>=1.8.1 in c:\users\wenur\appdata\local\programs\python\python313\lib\site-packages (from gensim) (8.0.2)
Requirement already satisfied: wrapt in c:\users\wenur\appdata\local\programs\python\python313\lib\site-packages (from smart_open>=1.8.1->gensim) (2.5.0)
Note: you may need to restart the kernel to use updated packages.
Word2Vec imported successfully!

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [19]:
import pandas as pd
import numpy as np
import re

In [20]:
import gensim

print(gensim.__version__)

4.4.0

In [21]:
import pandas as pd

df = pd.read_csv(
    "../data/raw/DOB_ECB_Violations_20260913 (1).csv"
)

df.head()

C:\Users\wenur\AppData\Local\Temp\ipykernel_17752\3317146408.py:3: DtypeWarning: Columns (0: SECTION_LAW_DESCRIPTION3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

,ISN_DOB_BIS_EXTRACT,ECB_VIOLATION_NUMBER,ECB_VIOLATION_STATUS,DOB_VIOLATION_NUMBER,BIN,BORO,BLOCK,LOT,HEARING_DATE,HEARING_TIME,...,SECTION_LAW_DESCRIPTION7,INFRACTION_CODE8,SECTION_LAW_DESCRIPTION8,INFRACTION_CODE9,SECTION_LAW_DESCRIPTION9,INFRACTION_CODE10,SECTION_LAW_DESCRIPTION10,AGGRAVATED_LEVEL,HEARING_STATUS,CERTIFICATION_STATUS
0,1749575,39190613X,RESOLVE,NaN,2026562.0,2,3813.0,19.0,20260821,930,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,IN VIOLATION,CERTIFICATE ACCEPTED
1,1729620,39156049P,ACTIVE,NaN,1003388.0,1,279.0,69.0,20270415,830,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,PENDING,NaN
2,1801198,39193627K,ACTIVE,NaN,5020516.0,5,795.0,41.0,20260902,930,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,DEFAULT,NO COMPLIANCE RECORDED
3,1793922,39169086R,ACTIVE,NaN,4139680.0,4,6381.0,54.0,20260908,830,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,PENDING,NaN
4,1741922,35730749Y,ACTIVE,07222026SR07NS01,2016355.0,2,3277.0,2.0,20261030,830,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,PENDING,NaN

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 102467 entries, 0 to 102466
Data columns (total 46 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   ISN_DOB_BIS_EXTRACT        102467 non-null  int64
 1   ECB_VIOLATION_NUMBER       102467 non-null  str
 2   ECB_VIOLATION_STATUS       102467 non-null  str
 3   DOB_VIOLATION_NUMBER       21654 non-null   str
 4   BIN                        102372 non-null  float64
 5   BORO                       102467 non-null  int64
 6   BLOCK                      101980 non-null  float64
 7   LOT                        101980 non-null  float64
 8   HEARING_DATE               102467 non-null  int64
 9   HEARING_TIME               102467 non-null  int64
 10  SERVED_DATE                102467 non-null  int64
 11  ISSUE_DATE                 102467 non-null  int64
 12  SEVERITY                   102467 non-null  str
 13  VIOLATION_TYPE             102467 non-null  str
 14  RESPONDENT_NAME            102392 non-null  str
 15  RESPONDENT_HOUSE_NUMBER    79713 non-null   str
 16  RESPONDENT_STREET          94683 non-null   str
 17  RESPONDENT_CITY            94188 non-null   str
 18  RESPONDENT_ZIP             93535 non-null   str
 19  VIOLATION_DESCRIPTION      102459 non-null  str
 20  PENALITY_IMPOSED           102467 non-null  str
 21  AMOUNT_PAID                102467 non-null  str
 22  BALANCE_DUE                102467 non-null  str
 23  INFRACTION_CODE1           102467 non-null  str
 24  SECTION_LAW_DESCRIPTION1   94473 non-null   str
 25  INFRACTION_CODE2           2603 non-null    str
 26  SECTION_LAW_DESCRIPTION2   2125 non-null    str
 27  INFRACTION_CODE3           20 non-null      float64
 28  SECTION_LAW_DESCRIPTION3   20 non-null      str
 29  INFRACTION_CODE4           0 non-null       float64
 30  SECTION_LAW_DESCRIPTION4   0 non-null       float64
 31  INFRACTION_CODE5           0 non-null       float64
 32  SECTION_LAW_DESCRIPTION5   0 non-null       float64
 33  INFRACTION_CODE6           0 non-null       float64
 34  SECTION_LAW_DESCRIPTION6   0 non-null       float64
 35  INFRACTION_CODE7           0 non-null       float64
 36  SECTION_LAW_DESCRIPTION7   0 non-null       float64
 37  INFRACTION_CODE8           0 non-null       float64
 38  SECTION_LAW_DESCRIPTION8   0 non-null       float64
 39  INFRACTION_CODE9           0 non-null       float64
 40  SECTION_LAW_DESCRIPTION9   0 non-null       float64
 41  INFRACTION_CODE10          0 non-null       float64
 42  SECTION_LAW_DESCRIPTION10  0 non-null       float64
 43  AGGRAVATED_LEVEL           102467 non-null  str
 44  HEARING_STATUS             93663 non-null   str
 45  CERTIFICATION_STATUS       70646 non-null   str
dtypes: float64(18), int64(6), str(22)
memory usage: 36.0 MB

In [23]:
df["VIOLATION_DESCRIPTION"].head()

0    AS PER PREVIOUS REQUEST FOR CORRECTIVE ACTION ...
1    TEMP CONSTRUCTION EQUIP/INSTALLATION ON SITE E...
2    UNLAWFUL ACTS. FAILURE TO COMPLY WITH COMMISSI...
3    WORK WITHOUT A PERMIT. NOTED: OBSERVED WORK HA...
4    FAILURE TO PROVIDE UNOBSTRUCTED EXIT PASSAGEWA...
Name: VIOLATION_DESCRIPTION, dtype: str

In [24]:
text_df = df[["VIOLATION_DESCRIPTION"]]

In [25]:
text_df.head()

                               VIOLATION_DESCRIPTION
0  AS PER PREVIOUS REQUEST FOR CORRECTIVE ACTION ...
1  TEMP CONSTRUCTION EQUIP/INSTALLATION ON SITE E...
2  UNLAWFUL ACTS. FAILURE TO COMPLY WITH COMMISSI...
3  WORK WITHOUT A PERMIT. NOTED: OBSERVED WORK HA...
4  FAILURE TO PROVIDE UNOBSTRUCTED EXIT PASSAGEWA...

In [26]:
df["VIOLATION_DESCRIPTION"].isna().sum()

np.int64(8)

In [27]:
text_df = text_df.dropna()

In [28]:
import re


def clean_text(text):

    text = text.lower()

    text = re.sub(
        r'[^a-z\s]',
        '',
        text
    )

    return text.split()

In [29]:
text_df["tokens"] = (
    text_df["VIOLATION_DESCRIPTION"]
    .apply(clean_text)
)

In [30]:
text_df.head()

,VIOLATION_DESCRIPTION,tokens
0,AS PER PREVIOUS REQUEST FOR CORRECTIVE ACTION ...,"[as, per, previous, request, for, corrective, ..."
1,TEMP CONSTRUCTION EQUIP/INSTALLATION ON SITE E...,"[temp, construction, equipinstallation, on, si..."
2,UNLAWFUL ACTS. FAILURE TO COMPLY WITH COMMISSI...,"[unlawful, acts, failure, to, comply, with, co..."
3,WORK WITHOUT A PERMIT. NOTED: OBSERVED WORK HA...,"[work, without, a, permit, noted, observed, wo..."
4,FAILURE TO PROVIDE UNOBSTRUCTED EXIT PASSAGEWA...,"[failure, to, provide, unobstructed, exit, pas..."

In [31]:
%pip install nltk
import nltk

nltk.download("stopwords")

Requirement already satisfied: nltk in c:\users\wenur\appdata\local\programs\python\python313\lib\site-packages (3.10.3)
Requirement already satisfied: defusedxml in c:\users\wenur\appdata\local\programs\python\python313\lib\site-packages (from nltk) (0.7.1)
Requirement already satisfied: click in c:\users\wenur\appdata\local\programs\python\python313\lib\site-packages (from nltk) (8.5.0)
Requirement already satisfied: joblib in c:\users\wenur\appdata\local\programs\python\python313\lib\site-packages (from nltk) (1.6.0)
Requirement already satisfied: regex>=2021.8.3 in c:\users\wenur\appdata\local\programs\python\python313\lib\site-packages (from nltk) (2026.9.29)
Requirement already satisfied: tqdm in c:\users\wenur\appdata\local\programs\python\python313\lib\site-packages (from nltk) (4.70.1)
Requirement already satisfied: cloudpickle>=3.0 in c:\users\wenur\appdata\local\programs\python\python313\lib\site-packages (from joblib->nltk) (3.1.2)
Requirement already satisfied: colorama in c:\users\wenur\appdata\roaming\python\python313\site-packages (from tqdm->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\wenur\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [32]:
from nltk.corpus import stopwords

In [33]:
stop_words = set(stopwords.words("english"))

In [34]:
print(list(stop_words)[:10])

["couldn't", 'he', 'what', 'after', "he'll", 'themselves', "they're", 'out', "we'd", "i'll"]

In [35]:
def clean_text(text):

    text = text.lower()

    text = re.sub(
        r"[^a-z\s]",
        "",
        text
    )

    words = text.split()

    words = [
        word 
        for word in words 
        if word not in stop_words
    ]

    return words

In [36]:
text_df["tokens"] = (
    text_df["VIOLATION_DESCRIPTION"]
    .apply(clean_text)
)

In [37]:
text_df[["VIOLATION_DESCRIPTION","tokens"]].head()

,VIOLATION_DESCRIPTION,tokens
0,AS PER PREVIOUS REQUEST FOR CORRECTIVE ACTION ...,"[per, previous, request, corrective, action, i..."
1,TEMP CONSTRUCTION EQUIP/INSTALLATION ON SITE E...,"[temp, construction, equipinstallation, site, ..."
2,UNLAWFUL ACTS. FAILURE TO COMPLY WITH COMMISSI...,"[unlawful, acts, failure, comply, commissioner..."
3,WORK WITHOUT A PERMIT. NOTED: OBSERVED WORK HA...,"[work, without, permit, noted, observed, work,..."
4,FAILURE TO PROVIDE UNOBSTRUCTED EXIT PASSAGEWA...,"[failure, provide, unobstructed, exit, passage..."

In [38]:
Word2Vec(
    sentences=text_df["tokens"],
    vector_size=100,
    window=5,
    min_count=5
)

In [39]:
text_df["tokens"].head()

0    [per, previous, request, corrective, action, i...
1    [temp, construction, equipinstallation, site, ...
2    [unlawful, acts, failure, comply, commissioner...
3    [work, without, permit, noted, observed, work,...
4    [failure, provide, unobstructed, exit, passage...
Name: tokens, dtype: object

In [40]:
empty_count = text_df["tokens"].apply(len).eq(0).sum()

print(empty_count)

1

In [41]:
all_words = [
    word
    for tokens in text_df["tokens"]
    for word in tokens
]

print("Total words:", len(all_words))
print("Unique words:", len(set(all_words)))

Total words: 2028101
Unique words: 42825

In [42]:
from gensim.models import Word2Vec


w2v_model = Word2Vec(
    sentences=text_df["tokens"],
    vector_size=100,
    window=5,
    min_count=5,
    workers=4,
    seed=42
)

In [43]:
text_df.loc[
    text_df["tokens"].apply(len) == 0,
    "tokens"
] = [["unknown"]]

In [44]:
from collections import Counter

word_counts = Counter(
    word
    for tokens in text_df["tokens"]
    for word in tokens
)

word_counts.most_common(20)

[('observed', 53874),
 ('inspection', 39305),
 ('failure', 38027),
 ('building', 33422),
 ('time', 30878),
 ('permit', 28759),
 ('work', 25465),
 ('maintain', 21657),
 ('file', 19413),
 ('noted', 16637),
 ('certificate', 16070),
 ('without', 14264),
 ('floor', 14167),
 ('correction', 13936),
 ('code', 13573),
 ('construction', 12658),
 ('comply', 12553),
 ('installed', 12400),
 ('issued', 12337),
 ('per', 12068)]

In [45]:
from gensim.models import Word2Vec


w2v_model = Word2Vec(
    sentences=text_df["tokens"],
    vector_size=100,
    window=5,
    min_count=5,
    workers=4,
    seed=42
)

In [46]:
len(w2v_model.wv.index_to_key)

8834

In [47]:
w2v_model.wv["fire"]

array([ 1.5676465 , -0.8399153 ,  2.8143933 ,  1.4013987 , -2.4139202 ,
       -1.1878934 ,  1.3059905 ,  0.06676021, -0.3815993 , -1.3690839 ,
       -1.6406138 , -0.17580335, -1.9530375 ,  2.8904634 ,  0.38500735,
        0.1695772 ,  0.2996172 ,  0.26498678,  0.6616646 ,  2.788966  ,
        1.5816672 ,  3.0525823 , -1.6481618 , -1.0827785 , -3.213798  ,
        0.88546103, -0.94626534, -1.3643907 , -3.7068465 ,  2.5809543 ,
        2.7381008 , -1.0069674 ,  2.9491844 ,  0.78320414,  0.29580554,
        3.2522886 , -0.6821879 , -1.2239352 , -0.3186617 ,  0.54272825,
       -2.0606775 , -1.5380903 ,  2.3618429 ,  1.7444054 ,  1.7412049 ,
       -1.0729781 ,  1.8287867 ,  0.07950848, -2.8441837 , -1.2161701 ,
       -0.95653445,  2.4467509 ,  0.8411836 ,  0.79551816,  0.56717026,
       -4.3226867 , -2.1993291 ,  0.6113781 , -0.09819605,  2.8001869 ,
        1.8826914 , -2.899544  , -0.19005805,  0.6404341 , -3.3769784 ,
        3.5659332 , -3.6914692 ,  1.1282966 ,  0.04707378, -2.4687197 ,
        2.9021657 ,  1.4660418 ,  1.0459318 , -1.867281  ,  0.10602985,
       -2.375904  , -1.6792644 , -0.03805259, -2.3887317 ,  0.9585572 ,
        1.7996216 , -2.3166082 ,  1.0010376 , -0.68434113, -0.19404079,
       -0.34660614,  0.4295579 ,  2.565774  ,  0.45088455,  0.39636695,
       -0.3914133 ,  0.9654105 , -0.73095584,  0.15367566,  0.9117424 ,
        0.15341659, -0.91318554, -1.6491029 ,  1.1003344 , -0.52975845],
      dtype=float32)

In [48]:
w2v_model.wv.most_similar("fire", topn=10)

[('windowfire', 0.6273123621940613),
 ('hatch', 0.5720759034156799),
 ('resetting', 0.5020878314971924),
 ('landings', 0.44434428215026855),
 ('nonfire', 0.4323785901069641),
 ('fir', 0.41628071665763855),
 ('drop', 0.4031551480293274),
 ('obstructed', 0.39208343625068665),
 ('dropdown', 0.36251676082611084),
 ('flower', 0.361696720123291)]

In [49]:
len(w2v_model.wv.index_to_key)

8834

In [50]:
w2v_model.wv.most_similar("fire", topn=10)

[('windowfire', 0.6273123621940613),
 ('hatch', 0.5720759034156799),
 ('resetting', 0.5020878314971924),
 ('landings', 0.44434428215026855),
 ('nonfire', 0.4323785901069641),
 ('fir', 0.41628071665763855),
 ('drop', 0.4031551480293274),
 ('obstructed', 0.39208343625068665),
 ('dropdown', 0.36251676082611084),
 ('flower', 0.361696720123291)]

In [51]:
w2v_model.wv.most_similar("building", topn=10)

[('buildings', 0.5864821076393127),
 ('bldg', 0.5711230635643005),
 ('house', 0.5700548887252808),
 ('midblock', 0.5343683958053589),
 ('premises', 0.4838760793209076),
 ('buildingi', 0.44141343235969543),
 ('home', 0.4225170910358429),
 ('property', 0.41039201617240906),
 ('build', 0.4029613733291626),
 ('ftmb', 0.3915298283100128)]

In [52]:
w2v_model.wv.most_similar("failure", topn=10)

[('failed', 0.5290491580963135),
 ('ftmb', 0.520809531211853),
 ('faiure', 0.46353772282600403),
 ('ftm', 0.4584091603755951),
 ('maintain', 0.4483599364757538),
 ('thereof', 0.4300421178340912),
 ('failiure', 0.40119045972824097),
 ('failing', 0.39811766147613525),
 ('rfailure', 0.39690321683883667),
 ('mannerfailure', 0.3964393436908722)]